const express = require("express")
const Dashboard = require("./componets/dashboard")
const CheckSetup = require("./componets/checkSetup")
const VerrifyUserName = require("./componets/verrifyUsername")
const Setup = require("./componets/setup")
const ChangeGalaPrice = require("./componets/changeGalaPrice")
const Setting = require("./componets/setting")
const Activate = require("./componets/activate")
const Page = require("./componets/page")
const Payment = require("./componets/payment")
const authMiddleware = require("../authMiddleWare")
const Support = require("./componets/support")
const CheckoutData = require("./componets/checkoutData")
const Withdraw = require("./componets/withdraw")
const Nav = require("./componets/nav")
const Explore = require("./componets/explore")
const UpdateGoal = require("./componets/goal")
const { AlertsFeed, TriggerTestAlert } = require("./componets/alerts")
const SubmitKyc = require("./componets/kyc")

const route = express.Router()

route.get("/explore", Explore)
route.get("/alerts-feed", AlertsFeed)
route.post("/test-alert", authMiddleware, TriggerTestAlert)
route.post("/goal", authMiddleware, UpdateGoal)
route.post("/submit-kyc", authMiddleware, SubmitKyc)
route.post("/dashboard",authMiddleware,Dashboard)
route.post("/setting",authMiddleware,Setting)
route.get("/checkSetup/:email",authMiddleware,CheckSetup)
route.post("/check-username",authMiddleware,VerrifyUserName)
route.post("/changePrice",authMiddleware,ChangeGalaPrice)
route.post("/setup",authMiddleware,Setup)
route.post("/activate",authMiddleware,Activate)
route.post("/page",Page)
route.post("/payment",Payment)
route.post("/support",Support)
route.post("/checkoutData",authMiddleware,CheckoutData)
route.post("/withdraw",authMiddleware,Withdraw)
route.post("/nav",authMiddleware,Nav)


module.exports = route